.github/workflows/python.yml, .gitmodules, python/sedonadb/python/sedonadb/testing.py, python/sedonadb/tests/conftest.py, python/sedonadb/tests/io/test_parquet.py, submodules/download-assets.py
Adds a basic suite of tests to check metadata, pruning, and spatialness of Parquet reads. Notably, this includes realistic checks of a multi-file dataset single GeoParquet 1.1 file with row groups to ensure correctness of queries we should be pruning.
=> chore(python/sedonadb): Add integration tests for GeoParquet reader

.github/workflows/rust.yml, rust/sedona-testing/src/benchmark_util.rs
Rust CI is taking almost an hour and I think we can do better:
- Clippy, Documentation, and Tests all have slightly different compile flags and I think the cache isn't particularly efficient for any of them (and running all of them in one job results in all the disk space getting used up for the runner)
- All three are happening in serial instead of in parallel
- It's running on Python and docs PRs that don't affect Rust code
- The benchmarks were running on big ish data which was slow (especially in a debug build)
Let's see if this is better!
=> chore(ci): Separate Rust CI tasks into concurrent jobs

python/sedonadb/tests/functions/test_transforms.py, rust/sedona-functions/src/st_setsrid.rs
After this change, using code 0 in `ST_SetSrid` unsets the CRS.
Updated the UDF to check for the 0 code.
- Added unit test
- Added an integration test
- Added additional integration tests for `ST_SetSrid`
```
> select ST_SetSrid(ST_GeomFromText('POINT (1 1)'), 4326)
;
┌─────────────────────────────────────────────────────────────┐
│ st_setsrid(st_geomfromwkt(Utf8("POINT (1 1)")),Int64(4326)) │
│                       wkb <ogc:crs84>                       │
╞═════════════════════════════════════════════════════════════╡
│ POINT(1 1)                                                  │
└─────────────────────────────────────────────────────────────┘
1 row(s)/1 column(s) fetched. 
Elapsed 0.024 seconds.
> select ST_SetSrid(ST_SetSrid(ST_GeomFromText('POINT (1 1)'), 4326), 0); …
```
=> Add Unset code for ST_SetSrid

rust/sedona-functions/src/st_setsrid.rs
CI is failing in unrelated PRs because there's a missing arg here. Seems like a classic case of ci merging two PRs without re-testing ci after the first one merged
=> bug: Add missing arg to call_udf in setsrid test

docs/README.md, docs/requirements.txt, python/sedonadb/python/sedonadb/context.py
`sedonadb` package must be installed to build documentation using mkdocs. I have added `sedonadb[geopandas]` to the requirements.txt file although it is not published to PyPI for now. The package name was taken from https://github.com/apache/sedona/pull/2328.
I wrote the docstring for `create_data_frame` according to my understanding of the code. Feel free to point out any problem.
=> Fix docs for building documentation using mkdocs, add docstring for `create_data_frame`

python/sedonadb/tests/functions/test_predicates.py, rust/sedona-common/src/option.rs, rust/sedona/src/context.rs
This patch uses TG as the default library for evaluating spatial predicates. TG has better overall performance compared to GEOS, but it does not always produce the same result as GEOS. See the skipped python test for an example.
Here are the benchmark results of ST_Contains.
After switching to TG:
```
------------------------------------------------------------------------------------------ benchmark 'table=polygons_complex': 6 tests -------------------------------------------------------------------------------------------
Name (time in ms)                                       Min                    Max                   Mean              StdDev                 Median                 IQR            Outliers     OPS            Rounds  Iterations …
```
=> Use spatial predicates defined by TG when tg feature is enabled

rust/sedona-functions/src/lib.rs, rust/sedona-functions/src/register.rs, rust/sedona-functions/src/st_srid.rs, rust/sedona-schema/src/crs.rs
This change adds `ST_SRID` to retrieve a geometry's CRS' SRID.
This is the first step in #28 .  Will implement #29 before adding the integration tests to align the schemas.
```
> select ST_SRID(ST_SetSrid(ST_GeomFromText('POINT (1 1)'), 'EPSG:4837')) as srid;
┌────────┐
│  srid  │
│ uint32 │
╞════════╡
│   4837 │
└────────┘
```
=> Add ST_SRID

python/sedonadb/tests/test_context.py, rust/sedona-geoparquet/src/provider.rs
This one was pretty annoying to debug. Here's what was going on. We were calling `.to_urls()` in twice: once in `geoparquet_listing_table` and once in here in `context.rs`'s read_parquet:
https://github.com/apache/sedona-db/blob/5d3cfba252ffdb0d1a8ac1fd2126fb829ca459df/rust/sedona/src/context.rs#L229-L235
The second call was causing the `ListingTableUrl`'s glob attribute to being removed. I fixed this my removing one of the calls.
Note: globbing with the `*` operations still does NOT work on AWS s3 paths. That would need an additional fix / feature. It looks like Datafusion doesn't support globbing s3 paths yet either: It looks like DataFusion doesn't support globbing s3 paths yet either: https://github.com/apache/datafusion/issues/16303
=> bug: Support read_parquet glob file paths

python/sedonadb/python/sedonadb/_scarf.py, python/sedonadb/python/sedonadb/adbc.py, python/sedonadb/python/sedonadb/context.py, python/sedonadb/python/sedonadb/dbapi.py, rust/sedona/src/context.rs, rust/sedona/src/lib.rs, rust/sedona/src/scarf.rs, sedona-cli/src/main.rs
Scarf is allowed by the Apache Foundation Foundation: https://privacy.apache.org/policies/privacy-policy-public.html
Details and privacy statements can be found [here](https://about.scarf.sh/privacy-policy)
=> chore: add Scarf package to track usage

Cargo.lock, rust/sedona-expr/Cargo.toml, rust/sedona-expr/src/lib.rs, rust/sedona-expr/src/spatial_filter.rs, rust/sedona-expr/src/utils.rs, rust/sedona-geometry/src/bounding_box.rs, rust/sedona-geometry/src/interval.rs, rust/sedona-geoparquet/Cargo.toml, rust/sedona-geoparquet/src/format.rs, rust/sedona-spatial-join/src/operand_evaluator.rs, rust/sedona-spatial-join/src/optimizer.rs
This patch pushes all spatial predicates when reading GeoParquet files, including distance predicate and all spatial relation operators such as `ST_Contains`, `ST_Within`, etc. To implement this, we have added the following methods to `BoundingBox`:
* `contains`: Check for bounding box containment
* `expand_by`: Expand the bounding box by the specified distance
The interval types also have corresponding functions implemented to work with 1-D plain and wrapping-around intervals.
Currently GeoParquet predicate pushdown only work with planar geometries correctly. This limitation already exists prior to developing this patch. I suggest that we submit another PR to disable spatial predicate pushdown for GeoParquet files containing spherical geography objects.
=> Push down all spatial predicates when reading GeoParquet files

Cargo.lock, c/sedona-geos/src/st_dwithin.rs, rust/sedona-geo/benches/geo-functions.rs, rust/sedona-geo/src/lib.rs, rust/sedona-geo/src/register.rs, rust/sedona-geo/src/st_distance.rs, rust/sedona-geo/src/st_dwithin.rs
This patch implements ST_Distance and ST_DWithin using georust/geo's Euclidean distance function.
Performance comparison with GEOS-based implementation:
GEO:
```
geo-st_distance-ArrayScalar(Point, Polygon(10))
time:   [19.120 ms 19.171 ms 19.227 ms]
geo-st_distance-ArrayScalar(Point, Polygon(500))
time:   [446.14 ms 448.10 ms 450.64 ms]
```
GEOS:
```
geos-st_distance-ArrayScalar(Polygon(10), Polygon(10))
time:   [187.51 ms 188.38 ms 189.72 ms]
geos-st_distance-ArrayScalar(Polygon(10), Polygon(500))
time:   [2.8651 s 2.8735 s 2.8822 s]
```
Benchmarking ternary functions such as ST_DWithin takes forever, it could be a problem with our benchmarking framework.
=> ST_Distance and ST_DWithin based on georust/geo

Cargo.lock, Cargo.toml, python/sedonadb/Cargo.toml, python/sedonadb/python/sedonadb/dataframe.py, python/sedonadb/src/dataframe.rs, python/sedonadb/tests/io/test_parquet.py, python/sedonadb/tests/test_dataframe.py, rust/sedona-geoparquet/Cargo.toml, rust/sedona-geoparquet/src/format.rs, rust/sedona-geoparquet/src/lib.rs, rust/sedona-geoparquet/src/metadata.rs, rust/sedona-geoparquet/src/options.rs, rust/sedona-geoparquet/src/provider.rs, rust/sedona-geoparquet/src/writer.rs, rust/sedona/Cargo.toml, rust/sedona/src/context.rs
This PR adds a writer for Parquet that writes GeoParquet metadata for output with spatial columns. Currently this doesn't write a bbox because that requires something a bit more sophisticated than just popping some metadata into the Parquet write options.
```python
import sedonadb
sd = sedonadb.connect()
sd.sql("SELECT ST_SetSRID(ST_GeomFromText('POINT (0 1)'), 4326) as geometry").to_parquet("foofy.parquet")
sd.read_parquet("foofy.parquet").show()
#> ┌────────────┐
#> │  geometry  │
#> │  geometry  │
#> ╞════════════╡
#> │ POINT(0 1) │
#> └────────────┘
```
=> feat(rust/sedona-geoparquet): Add GeoParquet writer for non-spatial output

.github/workflows/packaging.yml, .gitignore
Migrated documentation deployment from manual git operations to mike mkdocs with automated versioning based on branch patterns.
- **Replaced manual git operations** with mike deploy commands
- **New branching strategy**: 
- `main` → deploys as `latest-snapshot`
- `branch-x.y.z` → deploys as version `x.y.z` and sets as latest/default
- PRs → build artifacts only, no deployment
- **Consolidated jobs**: Merged `docs` and `update-asf-site` into single `docs-and-deploy` job
- **Removed workflow dispatch**: Fully automated based on branch patterns
- Automated version management
- Cleaner, more efficient workflow
- Better maintainability with mike's built-in features
=> Update the github action to leverage mike for versioned doc

.github/workflows/python-wheels.yml, c/sedona-proj/src/proj.rs
When pushing to main, we need the Python development version to be set to a unique value, or the nightly gemfury repository will reject the upload. However, when releasing, we need the wheels to have the right version!
This PR also fixes the branch specification for the release branch (i.e., `branch-*` and not `maint-*`).
Windows wheel builds were failing because on Windows `PJ_LOG_LEVEL` is an `enum` with `i32` storage (whereas it's unsigned storage on Posix).
=> fix(ci): Don't set development version for wheel on a release branch and fix Windows wheel builds

rust/sedona-functions/src/st_collect.rs
The ST_Collect() aggregator had a few places where the intermediate binary that was being collected had a full copy created. I think the on the DataFusion end there's a full copy created as well but at least today I don't think we can do anything about that.
```
native-st_collect-Array(Point)
time:   [1.9956 ms 2.0059 ms 2.0153 ms]
change: [-9.2224% -8.4076% -7.5286%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high severe
native-st_collect-Array(LineString(10))
time:   [4.9540 ms 5.0563 ms 5.1583 ms]
change: [-25.314% -23.234% -21.164%] (p = 0.00 < 0.05)
Performance has improved.
```
=> fix(rust/sedona-functions): Eliminate some intermediary copies in ST_Collect()

python/sedonadb/python/sedonadb/context.py
This PR improves the error a user sees if pyproj is unavailable or for some reason the configuration fails. This shouldn't happen when users `pip install "apache-sedona[db]"` because it is installed for them; however, it can happen if somebody runs `pip install sedonadb` by accident. It now reads:
```python
UserWarning: Failed to configure PROJ. Is pyproj or a system install of PROJ available?
Details: tried ['pyproj', 'conda', 'homebrew', 'system']
pyproj: No module named 'pyproj'
...more details
```
=> chore(python/sedonadb): Improve error message when pyproj is not installed

rust/sedona-functions/src/executor.rs, rust/sedona-functions/src/st_geometrytype.rs
Hi 👋🏼 , I’m new to the project and still learning my way around. `sedona-db` looks great, and I’d really appreciate any feedbacks.
Before, the execution logic for `st_geometrytype()` function is, for each row, first parse the `WKB` binary into a `WKB` object, then extract the base type from the object. This approach includes parsing unused fields in the `WKB` binary, since only the geometry type is needed.
This PR let it iterate through the raw `WKB` bytes, and directly parse the bytes to get the geometry type.
1. Extend `GenericExecutor` with a new API `execute_wkb_bytes_void()` to iterate on raw `WKB` bytes.
2. Implement a util to parse the type from `WKB` binary according to the spec.
3. Update `st_geometrytype()` with 1 and 2
I think it's better to move `2` to `wkb` crate, it doesn't …
=> perf: Faster `st_geometrytype()` function

python/sedonadb/python/sedonadb/dataframe.py, python/sedonadb/src/schema.rs, python/sedonadb/tests/test_dataframe.py, rust/sedona-schema/src/crs.rs, rust/sedona-schema/src/datatypes.rs, rust/sedona/src/show.rs
This PR ensures we print the "logical type name" (term invented in this PR), which is what we show in the display table header, and a more verbose description of the type when printing a schema and we have the whole width of the console at our disposal. The output looks like this:
```python
import sedonadb
sd = sedonadb.connect()
sd.sql("SELECT ST_Point(0, 1) as geom, 1 as one").schema
#> SedonaSchema with 2 fields:
#>   geom: geometry<Wkb>
#>   one: non-nullable int64<Int64>
```
This PR implements the logical type name for arrow types too, so columns with those types have potentially shorter type names in tabular display (e.g., `struct(all the struct fields)` is now just `struct` in the tabular display.
Happy to workshop any of that...coming up with these names is hard!
=> fix(python/sedonadb): Ensure schema displays "geometry" and "geography" for spatial types

python/sedonadb/python/sedonadb/dataframe.py, python/sedonadb/src/dataframe.rs, python/sedonadb/tests/test_dataframe.py
This PR adds `.execute()` to make it more intuitive what to do for a CREATE/SET query. Functionally it is very similar to .count() but doesn't actually use DataFusion's counter under the hood to avoid any issue with optimizations from that.
```python
import sedonadb
sd = sedonadb.connect()
sd.sql("CREATE OR REPLACE VIEW temp_view AS SELECT 1 as one").execute()
sd.view("temp_view").show()
#> ┌───────┐
#> │  one  │
#> │ int64 │
#> ╞═══════╡
#> │     1 │
#> └───────┘
```
=> feat(python/sedonadb): Add DataFrame.execute() for non-result queries

python/sedonadb/python/sedonadb/__init__.py, python/sedonadb/python/sedonadb/_options.py, python/sedonadb/python/sedonadb/context.py, python/sedonadb/python/sedonadb/dataframe.py, python/sedonadb/tests/test_context.py, python/sedonadb/tests/test_dataframe.py
Previously we had global options, however, the way we had structured the `sedona.db` import resulted in the options being completely inaccessible (i.e., `sedona.db.options.interactive = True` didn't work!).
This PR scopes the options to the context, which is probably better anyway because the `sd` object is the one most people are interacting with anyway.
```python
import sedona.db
sd = sedona.db.connect()
sd.options.interactive = True
sd.sql("SELECT 1")
#> ┌──────────┐
#> │ Int64(1) │
#> │   int64  │
#> ╞══════════╡
#> │        1 │
#> └──────────┘
```
=> refactor(python/sedonadb): Scope options to the SedonaContext

.github/workflows/dev.yml, Cargo.lock, rust-toolchain.toml, rust/sedona-spatial-join/src/refine/geo.rs
The generic `DistanceExt` function should work well for now, switching the distance evaluator of spatial join to DistanceExt passes all tests.
This patch also upgraded the dependencies, especially the commit hash of `geo-generic-alg`, to ensure that we'll use the updated `DistanceExt` function.
=> Use distance_ext for evaluating ST_DWithin/ST_Distance in spatial join and upgrade dependencies

r/sedonadb/configure.win, r/sedonadb/src/Makevars.win.in
I succeeded to compile R sedonadb package on my local with https://github.com/apache/sedona-db/pull/114 and https://github.com/apache/datafusion/issues/17687. But, besides it, I found `configure.win` and `Makevars.win.in` needs a few tweaks to match with `configure` and `Makevars.in`.
=> fix(r/sedonadb): Add missing settings to configure.win and Makevars.win.in

.github/workflows/r.yml, c/sedona-proj/README.md, c/sedona-tg/README.md
I confirmed my pull request to datafusion (https://github.com/apache/datafusion/pull/17688) will enable the Windows CI for R package. Note that the latest version of datafusion is already v50 while sedona-db uses v49. So, I think this won't happen very soon.
my experiment: https://github.com/yutannihilation/sedona-db/pull/1
diff: https://github.com/apache/datafusion/compare/49.0.2...yutannihilation:datafusion:49.0.2-pr-17688
Until the day, this pull request adds some necessary tweaks for Windows. Also, this includes a typo fix found in https://github.com/apache/sedona-db/pull/114#discussion_r2365915732
=> chore(r/sedonadb): Add necessary tweaks for Windows CI on the R package

README.md
Currently, the URL of "Check out our comprehensive docs" points to a non-existent website. I'm not sure if there's a plan to actually use this URL at some point, but probably it's good to use <https://sedona.apache.org/sedonadb> for now.
=> docs: Fix a documentation link in README

Cargo.lock, r/sedonadb/src/Makevars.in, r/sedonadb/src/Makevars.win.in, rust-toolchain.toml
We've worked around the Rust compiler 1.90.0 regression in its forked dependency wherobots/geo: https://github.com/wherobots/geo/pull/11. Please refer to the description of that PR for details.
Once we resolve the compilation issue, we'll start working on moving geo-traits-ext and geo-generic-alg modules into the sedona-db repository, and get rid of our own geo, wkb, and wkt fork. This will unblock us from publishing our sedona-db crate to crates.io, and make the project grow in a healthier state.
=> fix: Workaround the Rust compiler 1.90.0 regression

.github/workflows/r-extended.yml, .github/workflows/r.yml, Cargo.lock, Cargo.toml, r/sedonadb/DESCRIPTION, r/sedonadb/R/zzz.R, r/sedonadb/bootstrap.R, r/sedonadb/src/.gitignore, r/sedonadb/src/Makevars.win.in
We're building in R Universe now! https://paleolimbot.r-universe.dev/sedonadb
We have some WARNINGs from missing declared dependencies (my fault) and a build failure for Windows (path length related to the CMake builder for the AWS dependency) and WebR (which I don't attempt to solve here).
=> fix(r/sedonadb): Increase CMAKE path length allowed on Windows and fix CMD check WARNINGs

.github/workflows/r.yml, r/sedonadb/src/Makevars.win.in
It looks like the R Universe runner hasn't enabled long path support (or the GitHub runner we're using builds everything in a shorter starting directory). This uses the cc builder for the AWS dependency and sets the optimization flag. This is not ideal but is better than a no Windows build or a Windows build without AWS.
=> chore(r/sedonadb): Try to fix Windows build

r/sedonadb/src/Makevars.win.in, r/sedonadb/src/rust/aws-lc-sys-win-toolchain.cmake
Another attempt to workaround the path length on Windows. I'm not sure if this will fix anything but it's worth a shot!
=> chore(r/sedonadb): Set the CMAKE_TOOLCHAIN_FILE for aws-lc-sys

r/sedonadb/src/Makevars.in, r/sedonadb/src/Makevars.win.in
Fix #164
When `-pedantic` flag is passed via `CFLAGS`, the aws-lc-sys crate cannot be compiled. `R CMD INSTALL` is not the case, so the CI is fine without this. However, when using devtools or pak, this flag is passed via pkgbuild. 
Why? Pkgbuild's comment says this flag is to "enforce good coding practice" to the R package developers. Also, it says this flag is used on CRAN check. But, considering this package doesn't strongly aim for CRAN (at least at the moment), probably it's fine to ignore the warnings.
https://github.com/r-lib/pkgbuild/blob/d88519a177c18c6a2701e1eaf9fb22d37f9580b9/R/compiler-flags.R#L3-L5
This pull request simply tries to override `-pedantic` by `-Wno-pedantic`. In the current `Makevars.win.in`, I used `substr` to remove `-pedantic` flag. However, it seems appending …
=> fix(r/sedonadb): Add -Wno-pedantic to avoid compile error

benchmarks/README.md, benchmarks/test_bench_base.py, benchmarks/test_functions.py
Follow up to https://github.com/apache/sedona-db/pull/183, this PR adds the pytest-benchmarks for ST_Azimuth, which uses a new `points_simple` table. Additionally, it updates the docs to recommend only running one benchmark at a time.
Result of ST_Azimuth benchmark
=> feat: Add ST_Azimuth benchmark and update benchmarking docs
